apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: andreazevedo80/app-cicd-dio:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 80
    NodePort: 30005
